config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :records
  resources :users
  resources :relationships,       only: [:create, :destroy]

  patch  'promote' => 'users#promote'
  patch  'demote' => 'users#demote'

  devise_scope :user do
    authenticated :user do
      root 'records#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :name, presence: true
  validates :contract, presence: true
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
  belongs_to :project 
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :supervisor, class_name: "User"
  belongs_to :employee, class_name: "User"
  belongs_to :project, class_name: "Project"
  validates :supervisor_id, presence: true
  validates :employee_id, presence: true
  validates :project_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :records
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "supervisor_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "employee_id",
                                   dependent:   :destroy
  has_many :employing, through: :active_relationships, source: :employee
  has_many :jobs, through: :passive_relationships, source: :project
  has_many :projects
  
  def promote(other_user)
    other_user.update_column(supervisor:true)
  end

  def hire(other_user, project_id)
    active_relationships.create(employee_id: other_user.id, project_id: project_id)
  end

  def fire(other_user, project)
    active_relationships.find_by(employee_id: other_user.id, project_id: project_id).destroy
  end

  def rostered?(other_user)
    employing.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore
    flash[:warning] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = policy_scope(Project)
    @users = User.all.where("supervisor = ?", true)
  end

  def show
    @project = Project.find(params[:id])
    @pm = User.find(@project.user_id)
    @users = User.all
    @supervisor_ids = Relationship.all.where("supervisor_id = ? and project_id = ?", @project.user_id, @project.id).pluck(:employee_id)
    @supervisors = User.where({id: @supervisor_ids})
    @employees = {}
    @relationships = []
    for supervisor in @supervisor_ids
      @relationships = Relationship.all.where("supervisor_id = ? and project_id = ?", supervisor, @project.id).pluck(:employee_id)
      @employees[supervisor] = User.where({id: @relationships})
    end
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      render json: @project
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      render json: @project
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @project = Project.find(params[:id])
    authorize @project
    @project.destroy
    head :no_content
  end

  private

    def project_params
      params.require(:project).permit(:name, :content, :user_id, :contract)
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @records = policy_scope(Record)
    @projects = policy_scope(Project)
  end

  def create
    @record = current_user.records.build(record_params)
    @record.name = current_user.email
    if @record.save
      render json: @record
    else
      render json: @record.errors, status: :unprocessable_entity
    end
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      render json: @record
    else
      render json: @record.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @record = Record.find(params[:id])
    authorize @record
    @record.destroy
    head :no_content
  end

  private

    def record_params
      params.require(:record).permit(:title, :amount, :date, :approved, :isHours, :project_id)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    if current_user.admin? or current_user.id == Project.find(params[:project_id]).user_id
      @relationship = Relationship.new(supervisor_id: params[:supervisor_id], employee_id: params[:employee_id], project_id: params[:project_id])
      @employee = User.find(params[:employee_id])
      if @relationship.save
        render json: @employee
      else
        render json: @employee.errors, status: :unprocessable_entity
      end
    end
  end

  def destroy
    if current_user.admin? or current_user.id == Project.find(params[:project_id]).user_id
      @relationship = Relationship.where(supervisor_id: params[:supervisor_id], employee_id: params[:employee_id], project_id: params[:project_id]).delete_all
      @employee = User.find(params[:employee_id])
      if @relationship
        render json: @employee
      else
        render json: @employee.errors, status: :unprocessable_entity
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all.where("id != ?", current_user.id).paginate(page: params[:page])
  end

  def promote
    @user = User.find(params[:employee_id])
    @user.supervisor = true
    @user.save
    respond_to do |format|
      format.html { redirect_to action: "index", controller: "users" }
      format.js
    end
  end

  def demote
    @user = User.find(params[:employee_id])
    @user.supervisor = false
    @user.save
    respond_to do |format|
      format.html { redirect_to action: "index", controller: "users" }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/layouts/_alert.html.erb
<div class="alert
    <%=
    case type.to_sym
    when :alert, :danger, :error, :validation_errors
        'alert-danger'
    when :warning, :todo
        'alert-warning'
    when :notice, :success
        'alert-success'
    else
        'alert-info'
    end
    %>
     alert-dismissible" role="alert">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <center><%= content %></center>
</div>

app/views/layouts/_header.html.erb
<ul class="nav nav-pills" role="tablist">
  <% if user_signed_in? %>
    <li role="presentation"><%= link_to "Records", records_path %></li>
    <li role="presentation"><%= link_to "Projects", projects_path %></li>
    <li role="presentation"><%= link_to "Users", users_path %></li>


  <ul class="nav navbar-nav pull-right">
    <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
  </ul>
  <% else %>
  <ul class="navbar-header pull-right">
    <li><%= link_to "Login", new_user_session_path %></li>
  </ul>
  <% end %>
</ul>

app/views/layouts/_messages.html.erb
<% flash.each do |type, content| %>
    <% if content.respond_to?('each')
        content.each do |item| %>
            <%= render 'layouts/alert',
                type: type,
                content: item %>
        <% end %>
    <% else %>
        <%= render 'layouts/alert',
                type: type,
                content: content %>
    <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accounts</title>
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, target-densitydpi=device-dpi">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/messages' %>
  <%= yield %>
</body>
</html>

app/views/projects/index.html.erb
<%= react_component 'Projects', { data: @projects, current_user: current_user, users: @users } %>

app/views/projects/show.html.erb
<%= react_component 'ProjectManage', { pm: @pm, project: @project, supervisors: @supervisors, employees: @employees, users: @users } %>

app/views/records/index.html.erb
<%= react_component 'Records', { records: @records, current_user: current_user, projects: @projects } %>

app/views/relationships/create.js.erb
$("#roster_form").html("<%= escape_javascript(render('users/fire')) %>");

app/views/relationships/destroy.js.erb
$("#roster_form").html("<%= escape_javascript(render('users/hire')) %>");

app/views/users/_demote.html.erb
<%= form_for(current_user, url: demote_path)  do |f| %>
  <div><%= hidden_field_tag :employee_id, user.id %></div>
  <%= f.submit "Demote", class: "btn btn-warning" %>
<% end %>

app/views/users/_fire.html.erb
<%= form_for(current_user.active_relationships.find_by(employee_id: user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Fire", class: "btn btn-danger" %>
<% end %>

app/views/users/_hire.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :employee_id, user.id %></div>
  <%= f.submit "Hire", class: "btn btn-primary" %>
<% end %>

app/views/users/_promote.html.erb
<%= form_for(current_user, url: promote_path)  do |f| %>
  <div><%= hidden_field_tag :employee_id, user.id %></div>
  <%= f.submit "Promote", class: "btn btn-success" %>
<% end %>

app/views/users/_promote_form.html.erb
  <div id="promote_form">
  <% if user.supervisor? %>
    <% if current_user.admin? %>
      <%= render partial: 'demote', locals: { user: user } %>
    <% end %>
  <% else %>
    <% if current_user.supervisor? or current_user.admin? %>
      <%= render partial: 'promote', locals: { user: user } %>
    <% end %>
  <% end %>
  </div>

app/views/users/_roster_form.html.erb
  <div id="roster_form">
  <% if current_user.rostered?(user) and current_user.supervisor? %>
    <%= render partial: 'fire', locals: { user: user } %>
  <% elsif current_user.supervisor? %>
    <%= render partial: 'hire', locals: { user: user } %>
  <% end %>
  </div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.email, user %>
  <%= render partial: 'promote_form', locals: { user: user } %>
</li>

app/views/users/demote.js.erb
$("#promote_form").html("<%= escape_javascript(render('users/demote')) %>");

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h2>All users</h2>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/promote.js.erb
$("#promote_form").html("<%= escape_javascript(render('users/promote')) %>");